### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Pacerino** [Pacerino/pr0gramm_mocking#1]
### Hinzugefügte Funktionen

- [ ] Schreiben von Kommentaren
- [ ] Schreiben von Nachrichten
- [ ] Hinzufügen von Kommentaren
- [ ] Hochladen von Posts

## Hinzugefügte Routen
- [ ] Inbox
- [ ] User
- [ ] Items
- [ ] Tags
- [ ] Comments
- [ ] Contact
- [ ] Profile
